SPECIES_ABILITY_DATA = {
  #[:MEW, 0] => %i[ABOVEITALL],
  [:EEVEE, 0]   => %i[ADAPTED  BIOENGINEERING],
  [:ZORUA, 0]   => %i[ILLUSION RELENTLESSPURSUIT],
  [:ZOROARK, 0] => %i[ILLUSION RELENTLESSPURSUIT],
}.freeze