SPECIES_ABILITY_DATA = {
 #[:MEW, 0]        => %i[ABOVEITALL],

  [:CATERPIE, 0]   => %i[SHIELDDUST MULTISCALE],
  [:METAPOD, 0]    => %i[SHIELDDUST MULTISCALE],

  [:DITTO, 0]      => %i[IMPOSTER REALIST],

  [:EEVEE, 0]      => %i[ADAPTED  BIOENGINEERING],

  [:FOONGUS, 0]    => %i[REGENERATOR BURDENED],
  [:AMOONGUSS, 0]  => %i[REGENERATOR BURDENED],

  [:HAPPINY, 0]    => %i[SERENEGRACE CURIOUSMEDICINE],
  [:CHANSEY, 0]    => %i[SERENEGRACE CURIOUSMEDICINE],
  [:BLISSEY, 0]    => %i[SERENEGRACE CURIOUSMEDICINE],

  [:KANGASKHAN, 0] => %i[INNERFOCUS VITALSPIRIT],
  [:TEAMUJIN, 0]   => %i[INNERFOCUS VITALSPIRIT],

  [:LILLIPUP, 0]   => %i[BREAKTHROUGH INTIMIDATE],
  [:HERDIER, 0]    => %i[BREAKTHROUGH INTIMIDATE],
  [:STOUTLAND, 0]  => %i[BREAKTHROUGH INTIMIDATE],

  [:MAGIKARP, 0]   => %i[MULTISCALE SWIFTSWIM],

  [:MEOWTH, 0]     => %i[GILD ALLTHATGLITTERS],
  [:PERSIAN, 0]    => %i[GILD ALLTHATGLITTERS],

  [:SALANDIT, 0]   => %i[BACKFIRE DOMINEERING],
  [:SALAZZLE, 0]   => %i[BACKFIRE DOMINEERING],

  [:WEEDLE, 0]     => %i[SHIELDDUST MULTISCALE],
  [:KAKUNA, 0]     => %i[SHIELDDUST MULTISCALE],

  [:ZORUA, 0]      => %i[ILLUSION RELENTLESSPURSUIT],
  [:ZOROARK, 0]    => %i[ILLUSION RELENTLESSPURSUIT],
}.freeze