SPECIES_ABILITY_DATA = {
 #[:MEW, 0]       => %i[ABOVEITALL],
  [:EEVEE, 0]     => %i[ADAPTED  BIOENGINEERING],

  [:FOONGUS, 0]   => %i[REGENERATOR BURDENED],
  [:AMOONGUSS, 0] => %i[REGENERATOR BURDENED],

  [:LILLIPUP, 0]  => %i[BREAKTHROUGH INTIMIDATE],
  [:HERDIER, 0]   => %i[BREAKTHROUGH INTIMIDATE],
  [:STOUTLAND, 0] => %i[BREAKTHROUGH INTIMIDATE],

  [:SALANDIT, 0]  => %i[BACKFIRE DOMINEERING],
  [:SALAZZLE, 0]  => %i[BACKFIRE DOMINEERING],

  [:ZORUA, 0]     => %i[ILLUSION RELENTLESSPURSUIT],
  [:ZOROARK, 0]   => %i[ILLUSION RELENTLESSPURSUIT],
}.freeze