ABILITY_DATA = {
 #:ABOVEITALL        => { :desc => proc { _INTL("1111111") }, :details => proc { _INTL("2222222") }, },
  :ARCANEFINALE     => { :desc => proc { _INTL("Turns to Finale Form when only unfainted on team. Ignores the condition of a perfect battle.") }, },
  :CHEEKPOUCH       => { :desc => proc { _INTL("When the Pokémon eats a Berry, it restores 25% of its max health.") }, },
  :CHILLINGNEIGH    => { :desc => proc { _INTL("Raises Attack by 2 steps after knocking out any Pokémon.") }, },
  :DEFEATIST        => { :desc => proc { _INTL("Halves move damage when HP is greater than 50%.") }, },
  :DISCOLIGHTS      => { :desc => proc { _INTL("It changes secondary type to that of the dance moves it's about to use.") }, },
  :EMOTIONAURA      => { :desc => proc { _INTL("Upon entry, creates an Emotion Room for 4 turns, adding an ability every turn.") }, },
  :EXTRASCOOP       => { :desc => proc { _INTL("Upon entry, the Pokémon heals itself for 1/5th max HP. This can overheal.") }, },
  :GRIMNEIGH        => { :desc => proc { _INTL("Raises Sp. Atk by 2 steps after knocking out any Pokémon.") }, },
  :GYRESPINNER      => { :desc => proc { _INTL("Upon entry, traps each opponent in a whirlpool for one turn.") }, },
  :HEROICFINALE     => { :desc => proc { _INTL("Turns to Finale Form when only unfainted on team. Ignores the condition of a perfect battle.") }, },
  :HUBRIS           => { :desc => proc { _INTL("Raises Sp. Atk by 2 steps after knocking out any Pokémon.") }, },
  :IGNITIONCYCLE    => { :desc => proc { _INTL("Each turn, raises Speed by 4 steps and loses 1/8th max HP. If Speed was maxed, instead Speed and HP are reset.") }, },
  :ILLUSION         => { :desc => proc { _INTL("Comes out disguised as the Pokémon in back. Boosts move power by 20% in disguise.") }, },
  :MOXIE            => { :desc => proc { _INTL("Raises Attack by 2 steps after knocking out any Pokémon.") }, },
  :PERENNIALPAYLOAD => { :desc => proc { _INTL("After fainting from exploding, revives after six turns, but requires above 50% HP if caused by others.") }, },
  :PLURIPOTENCE     => { :desc => proc { _INTL("Copies opponents' species' legal Abilities.") }, },
  :REFRACTIVE       => { :desc => proc { _INTL("It changes secondary type to that of the pulse moves it's about to use.") }, },
  :SAPPER           => { :desc => proc { _INTL("Upon entry, traps each opponent in a sand tomb for one turn.") }, },
  :SHIFTINGFIST     => { :desc => proc { _INTL("It changes secondary type to that of the punching moves it's about to use.") }, },
  :SPEEDBOOST       => { :desc => proc { _INTL("Speed is raised by one step at the end of each of its turns.") }, },
  :SWIFTSTOMPS      => { :desc => proc { _INTL("The user's Speed is doubled while using kicking moves. Every third kicking hit must be a crit.") }, },
  :UNIDENTIFIED     => { :desc => proc { _INTL("The Pokémon is Mutant-type. If the Pokémon is Deoxys, it will have multiple movesets.") }, },
  :VERDANT          => { :desc => proc { _INTL("Powers up Grass-type moves of itself and its allies by 30%.") }, },
}.freeze