module Settings
  NUM_STORAGE_BOXES = 200

  # Button used for Text Skipping (Default = :X)
  TEXT_SKIP_KEY = :V

  # Button used for Fast Forward (Default = :F)
  FAST_FORWARD_KEY = :Q

  FAINT_HEALING_TURN = 10

  REST_HEALING_NUM = 5
  SWITCH_HEALING_NUM = 10

  BATTLE_ENDING_NUMB = 30
  BATTLE_ENDING_PLUS = 50

  ROWE_STAB_OFF      = 5
  ROWE_STAB_OFF_MONO = 10
  ROWE_STAB_DEF      = 5
  ROWE_STAB_DEF_MONO = 10

  KILL_PUNNISHMENT = 10

  EXP_RATE_BOOST   = 2
  MONEY_RATE_BOOST = 2
  CATCH_RATE_BOOST = 3

  ITEM_CLAUSE          = false
  BATTLE_NO_MONEY_LOSS = true
  COPY_PLAYER_TRIBE    = false

  DEFAULT_ITEMS = %i[SITRUSBERRY]
  UNRECOVERABLE = %i[LEPPABERRY]
end