name: Deploy Cable Club

on:
    pull_request:
        types: [closed]
        branches:
            - development

jobs:
    deploy:
        if: github.event.pull_request.merged == true
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Execute deployment script
              run: .\deploy_cableclub.ps1
              shell: pwsh
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
